packages:
  - "packages/*"
  - "examples/*"
  - "tests/*"

catalogs:
  # Solana ecosystem packages
  solana:
    "@solana/compat": "^5.0.0"
    "@solana/kit": "^5.0.0"
    "@solana/addresses": "^5.0.0"
    "@solana/codecs-core": "^5.0.0"
    "@solana/codecs-strings": "^5.0.0"
    "@solana/errors": "^5.0.0"
    "@solana/keys": "^5.0.0"
    "@solana/promises": "^5.0.0"
    "@solana/signers": "^5.0.0"
    "@solana/transactions": "^5.0.0"
    "@solana/transaction-confirmation": "^5.0.0"
    "@solana/transaction-messages": "^5.0.0"
    "@solana-program/system": "^0.9.0"
    "@solana-program/compute-budget": "^0.9.0"
    "@solana-program/token": "^0.5.1"
    "@wallet-standard/app": "^1.0.1"
    "@wallet-standard/base": "^1.1.0"
    "@wallet-standard/errors": "^0.1.1"
    "@wallet-standard/features": "^1.0.3"
    "@solana/wallet-standard-features": "^1.3.0"
    "@solana/web3.js": "^1.95.3"

  # Type definitions and TS ecosystem
  typescript:
    "typescript": "^5.6.3"
    "@types/node": "^24"
    "@types/react": "^19.0.0"

  # UI / React ecosystem
  react:
    "react": "^19.0.0"
    "react-dom": "^19.0.0"

  # Shared utilities (only if used widely)
  utils:
    "bs58": "^6.0.0"
    "zustand": "^5.0.0"
